name: Build Application
description: This action builds the application.

runs:
  using: 'composite'

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  
  - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
        python-version: 3.12
  
  - name: Install Poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependency
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    shell: bash
    if : steps.cached-poetry-dependency.outputs.cache-hit != 'true'
    run: poetry run make install
              
            
            

        
